import './globals.css' 
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Navbar from '@/components/navbar'
const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-gradient-to-t from-[#00001E] to-[#023A46]`}>
      <Navbar/> 
        <div className="container p-7 h-full ">
        {children}
        </div>
        </body>
    </html>
  )
}
